name: 'GitHub Action FT Integration'
description: 'Sends CI/CD data from GitHub Action to OpenText SDP / SDM.'
inputs:
  octaneUrl:
    description: 'Url of OpenText SDP / SDM instance'
    required: true
  octaneSharedSpace:
    description: 'Shared Space ID'
    required: true
  octaneWorkspace:
    description: 'Workspace ID'
    required: true
  octaneClientId:
    description: "OpenText SDP / SDM API Access Client ID"
    required: true
  octaneClientSecret:
    description: 'OpenText SDP / SDM API Access Client Secret'
    required: true
  gitHubToken:
    description: 'GitHub PAT'
    required: true
  serverBaseUrl:
    description: 'URL of the organization/repository in GitHub'
    required: false
  testingToolType:
    description: 'Testing framework to use for the test runner'
    required: false
  minSyncInterval:
    description: 'Minimum number of seconds to pass between 2 synchronizations'
    required: false
    default: "15"
  logLevel:
    description: 'Sets the log level (1-5): 1-trace, 2-debug, 3-info, 4-warn, 5-error'
    required: false
    default: "3"
runs:
  using: 'node20'
  main: 'dist/index.js'
